import React from "react";
import ReactDOM from "react-dom/client";
import { PayloadLexicalReactRenderer } from "./payloadLexicalReactRenderer";
import { PayloadLexicalReactRendererProps } from "./types";

const content: PayloadLexicalReactRendererProps["content"] = {
  root: {
    type: "root",
    format: "",
    indent: 0,
    version: 1,
    children: [
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 1,
        type: "heading",
        version: 1,
        tag: "h1",
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "heading",
        version: 1,
        tag: "h2",
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "heading",
        version: 1,
        tag: "h3",
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "heading",
        version: 1,
        tag: "h4",
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "heading",
        version: 1,
        tag: "h5",
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "heading",
        version: 1,
        tag: "h6",
      },
      {
        children: [],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
            type: "text",
            version: 1,
          },
          { type: "linebreak", version: 1 },
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. ",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 1,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. ",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "quote",
        version: 1,
      },
      {
        children: [],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            children: [
              {
                children: [
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Foo",
                        type: "text",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 1,
                    type: "listitem",
                    version: 1,
                    value: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Bar",
                        type: "text",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 1,
                    type: "listitem",
                    version: 1,
                    value: 2,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            children: [
                              {
                                detail: 0,
                                format: 0,
                                mode: "normal",
                                style: "",
                                text: "Baz",
                                type: "text",
                                version: 1,
                              },
                            ],
                            direction: "ltr",
                            format: "",
                            indent: 2,
                            type: "listitem",
                            version: 1,
                            value: 1,
                          },
                          {
                            children: [
                              {
                                children: [
                                  {
                                    children: [
                                      {
                                        detail: 0,
                                        format: 0,
                                        mode: "normal",
                                        style: "",
                                        text: "Foo",
                                        type: "text",
                                        version: 1,
                                      },
                                    ],
                                    direction: "ltr",
                                    format: "",
                                    indent: 3,
                                    type: "listitem",
                                    version: 1,
                                    value: 1,
                                  },
                                  {
                                    children: [
                                      {
                                        children: [
                                          {
                                            children: [
                                              {
                                                detail: 0,
                                                format: 0,
                                                mode: "normal",
                                                style: "",
                                                text: "Bar",
                                                type: "text",
                                                version: 1,
                                              },
                                            ],
                                            direction: "ltr",
                                            format: "",
                                            indent: 4,
                                            type: "listitem",
                                            version: 1,
                                            value: 1,
                                          },
                                        ],
                                        direction: "ltr",
                                        format: "",
                                        indent: 0,
                                        type: "list",
                                        version: 1,
                                        listType: "bullet",
                                        start: 1,
                                        tag: "ul",
                                      },
                                    ],
                                    direction: "ltr",
                                    format: "",
                                    indent: 3,
                                    type: "listitem",
                                    version: 1,
                                    value: 2,
                                  },
                                ],
                                direction: "ltr",
                                format: "",
                                indent: 0,
                                type: "list",
                                version: 1,
                                listType: "bullet",
                                start: 1,
                                tag: "ul",
                              },
                            ],
                            direction: "ltr",
                            format: "",
                            indent: 2,
                            type: "listitem",
                            version: 1,
                            value: 2,
                          },
                        ],
                        direction: "ltr",
                        format: "",
                        indent: 0,
                        type: "list",
                        version: 1,
                        listType: "bullet",
                        start: 1,
                        tag: "ul",
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 1,
                    type: "listitem",
                    version: 1,
                    value: 3,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                type: "list",
                version: 1,
                listType: "bullet",
                start: 1,
                tag: "ul",
              },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "listitem",
            version: 1,
            value: 1,
          },
        ],
        direction: null,
        format: "",
        indent: 0,
        type: "list",
        version: 1,
        listType: "bullet",
        start: 1,
        tag: "ul",
      },
      {
        children: [
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: "normal",
                style: "",
                text: "One",
                type: "text",
                version: 1,
              },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "listitem",
            version: 1,
            value: 1,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: "normal",
                style: "",
                text: "Two",
                type: "text",
                version: 1,
              },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "listitem",
            version: 1,
            value: 2,
          },
          {
            children: [
              {
                detail: 0,
                format: 0,
                mode: "normal",
                style: "",
                text: "Three",
                type: "text",
                version: 1,
              },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "listitem",
            version: 1,
            value: 3,
          },
          {
            children: [
              {
                children: [
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Three — One",
                        type: "text",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 1,
                    type: "listitem",
                    version: 1,
                    value: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: "normal",
                        style: "",
                        text: "Three — Two",
                        type: "text",
                        version: 1,
                      },
                    ],
                    direction: "ltr",
                    format: "",
                    indent: 1,
                    type: "listitem",
                    version: 1,
                    value: 2,
                  },
                ],
                direction: "ltr",
                format: "",
                indent: 0,
                type: "list",
                version: 1,
                listType: "number",
                start: 1,
                tag: "ol",
              },
            ],
            direction: "ltr",
            format: "",
            indent: 0,
            type: "listitem",
            version: 1,
            value: 4,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "list",
        version: 1,
        listType: "number",
        start: 1,
        tag: "ol",
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Align left",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Align center",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "center",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Align right",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "right",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Tab index 0",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Tab index 1",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 1,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Tab index 2",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 2,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 0,
            mode: "normal",
            style: "",
            text: "Tab index 3",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 3,
        type: "paragraph",
        version: 1,
      },
      {
        children: [],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 1,
            mode: "normal",
            style: "",
            text: "Bold",
            type: "text",
            version: 1,
          },
          { type: "linebreak", version: 1 },
          {
            detail: 0,
            format: 2,
            mode: "normal",
            style: "",
            text: "Italic",
            type: "text",
            version: 1,
          },
          { type: "linebreak", version: 1 },
          {
            detail: 0,
            format: 8,
            mode: "normal",
            style: "",
            text: "Underline",
            type: "text",
            version: 1,
          },
          { type: "linebreak", version: 1 },
          {
            detail: 0,
            format: 4,
            mode: "normal",
            style: "",
            text: "Strikethrough",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 3,
            mode: "normal",
            style: "",
            text: "BoldItalic",
            type: "text",
            version: 1,
          },
          { type: "linebreak", version: 1 },
          {
            detail: 0,
            format: 11,
            mode: "normal",
            style: "",
            text: "BoldItalicUnderline",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [
          {
            detail: 0,
            format: 16,
            mode: "normal",
            style: "",
            text: "Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
            type: "text",
            version: 1,
          },
        ],
        direction: "ltr",
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [],
        direction: null,
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [],
        direction: null,
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
      {
        children: [],
        direction: null,
        format: "",
        indent: 0,
        type: "paragraph",
        version: 1,
      },
    ],
    direction: "ltr",
  },
};

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <PayloadLexicalReactRenderer content={content} />
  </React.StrictMode>
);
